### ISSUE TITLE
Data completeness type inconsistent with openLCA interface

### ISSUE THREAD

**Issue by WesIngwersen** [GreenDelta/glad-rest-service#4]
Data completeness [is defined as a DOUBLE here](https://github.com/GreenDelta/glad-rest-service/blob/a6b52f0e5aa81c60895f7ee023b91e5fb8a765ec/src/main/java/com/greendelta/search/glad/rest/model/Index.java#L115) but it's an open text field in the openLCA interface.  Trying to put a dataset with text in this field therefore throws an HTTP 500 error because it doesn't pass data validation.

**Comment by WesIngwersen** [comment]
This issue should perhaps be moved to the [lca-collaboration-server-log](https://github.com/GreenDelta/lca-collaboration-server-log/) or the repo actually hosting the CS code because it's not necessarily an error in interpreting the GLAD metadata.  Unfortunately i found that the [GLAD metadata guidance](https://wedocs.unep.org/bitstream/handle/20.500.11822/22539/ReportWG3_final_Nov.%2017%20(1).pdf) does not clearly specify the data types for the different descriptors, so unless I am missing something there is no clear reference document on what these formats should be for the descriptors
@aciroth @sebastian-greve @okworx @ezrakahn

**Comment by okworx** [comment]
@WesIngwersen have a look at the [API documentation](https://rawgit.com/GreenDelta/glad-rest-service/master/index.html)

**Comment by WesIngwersen** [comment]
@okworx I agree that it's present in the documentation but it's not clear in the Metadata working group report on the descriptors so it's not clear if the types that the fields were assigned were the same as intended by the WG.   Assuming they are, the data types of these descriptors for GLAD should be maintained somewhere that the data providers can be directed to that is linked from that guidance  document. I would prefer a table like we use in Federal LCA Commons Elementary Flow list github to be in a new Glad WG2 repo so I might suggest something like that to that WG

**Comment by WesIngwersen** [comment]
https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/master/format%20specs/FlowList.md
is an example and in WG1 we will adopt a markdown like this for the mapping format in the new GLAD Elementaryflows repo

**Comment by WesIngwersen** [comment]
Issue was with the openLCA collaboration server..this has been solved
